.\" Man page for pidgeon
.\" Licensed under BSD-like License.
.\" Created by Petr Bena
.\"
.TH Pidgeon "IRC Client" "User Manual"
.SH NAME
pidgeon
\- launch pidgeon irc client

.SH DESCRIPTION
Pidgeon is open source irc client
.PP
.SH "AUTHOR"
Petr Bena
.br
Project home page: http://pidgeonclient.org/
