
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
	public partial class Main
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action ShutDownAction;
		private global::Gtk.Action ToolsAction;
		private global::Gtk.Action MIscAction;
		private global::Gtk.Action ShowAction;
		private global::Gtk.Action UserAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action AboutAction;
		private global::Gtk.Action HelpAction1;
		private global::Gtk.Action RootAction;
		private global::Gtk.Action SearchAction;
		private global::Gtk.Action SwitchToAdvancedLayoutAction;
		private global::Gtk.Action ConfigurationFileAction;
		private global::Gtk.Action OpenNewConnectionAction;
		private global::Gtk.Action OpenNewConnectionAction1;
		private global::Gtk.Action FavoriteNetworksAction;
		private global::Gtk.Action PreferencesAction;
		private global::Gtk.Action PacketViewerAction;
		private global::Gtk.Action SkinEditorAction;
		private global::Gtk.Action SmallChatAction;
		private global::Gtk.Action AttachToMicroChatAction;
		private global::Gtk.Action DetachFromMicroChatAction;
		private global::Gtk.VBox vbox3;
		private global::Gtk.MenuBar menubar2;
		private global::Gtk.HPaned hpaned1;
		private global::Client.Graphics.PidgeonList pidgeonlist1;
		private global::Gtk.Statusbar statusbar3;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Forms.Main
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", "File", null, null);
			this.FileAction.ShortLabel = "File";
			w1.Add (this.FileAction, null);
			this.ShutDownAction = new global::Gtk.Action ("ShutDownAction", "Shut down", null, null);
			this.ShutDownAction.ShortLabel = "Shut down";
			w1.Add (this.ShutDownAction, null);
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", "Tools", null, null);
			this.ToolsAction.ShortLabel = "Tools";
			w1.Add (this.ToolsAction, null);
			this.MIscAction = new global::Gtk.Action ("MIscAction", "MIsc", null, null);
			this.MIscAction.ShortLabel = "MIsc";
			w1.Add (this.MIscAction, null);
			this.ShowAction = new global::Gtk.Action ("ShowAction", "Show", null, null);
			this.ShowAction.ShortLabel = "Show";
			w1.Add (this.ShowAction, null);
			this.UserAction = new global::Gtk.Action ("UserAction", "User", null, null);
			this.UserAction.ShortLabel = "User";
			w1.Add (this.UserAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", "Help", null, null);
			this.HelpAction.ShortLabel = "Help";
			w1.Add (this.HelpAction, null);
			this.AboutAction = new global::Gtk.Action ("AboutAction", "About", null, null);
			this.AboutAction.ShortLabel = "About";
			w1.Add (this.AboutAction, null);
			this.HelpAction1 = new global::Gtk.Action ("HelpAction1", "Help", null, null);
			this.HelpAction1.ShortLabel = "Help";
			w1.Add (this.HelpAction1, null);
			this.RootAction = new global::Gtk.Action ("RootAction", "Root", null, null);
			this.RootAction.ShortLabel = "Root";
			w1.Add (this.RootAction, null);
			this.SearchAction = new global::Gtk.Action ("SearchAction", "Search", null, null);
			this.SearchAction.ShortLabel = "Search";
			w1.Add (this.SearchAction, null);
			this.SwitchToAdvancedLayoutAction = new global::Gtk.Action ("SwitchToAdvancedLayoutAction", "Switch to advanced layout", null, null);
			this.SwitchToAdvancedLayoutAction.ShortLabel = "Switch to advanced layout";
			w1.Add (this.SwitchToAdvancedLayoutAction, null);
			this.ConfigurationFileAction = new global::Gtk.Action ("ConfigurationFileAction", "Configuration file", null, null);
			this.ConfigurationFileAction.ShortLabel = "Configuration file";
			w1.Add (this.ConfigurationFileAction, null);
			this.OpenNewConnectionAction = new global::Gtk.Action ("OpenNewConnectionAction", "Open new connection", null, null);
			this.OpenNewConnectionAction.ShortLabel = "Open new connection";
			w1.Add (this.OpenNewConnectionAction, null);
			this.OpenNewConnectionAction1 = new global::Gtk.Action ("OpenNewConnectionAction1", "Open new connection", null, null);
			this.OpenNewConnectionAction1.ShortLabel = "Open new connection";
			w1.Add (this.OpenNewConnectionAction1, null);
			this.FavoriteNetworksAction = new global::Gtk.Action ("FavoriteNetworksAction", "Favorite networks", null, null);
			this.FavoriteNetworksAction.ShortLabel = "Favorite networks";
			w1.Add (this.FavoriteNetworksAction, null);
			this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", "Preferences", null, null);
			this.PreferencesAction.ShortLabel = "Preferences";
			w1.Add (this.PreferencesAction, null);
			this.PacketViewerAction = new global::Gtk.Action ("PacketViewerAction", "Packet viewer", null, null);
			this.PacketViewerAction.ShortLabel = "Packet viewer";
			w1.Add (this.PacketViewerAction, null);
			this.SkinEditorAction = new global::Gtk.Action ("SkinEditorAction", "Skin editor", null, null);
			this.SkinEditorAction.ShortLabel = "Skin editor";
			w1.Add (this.SkinEditorAction, null);
			this.SmallChatAction = new global::Gtk.Action ("SmallChatAction", "Small chat", null, null);
			this.SmallChatAction.ShortLabel = "Small chat";
			w1.Add (this.SmallChatAction, null);
			this.AttachToMicroChatAction = new global::Gtk.Action ("AttachToMicroChatAction", "Attach to micro chat", null, null);
			this.AttachToMicroChatAction.ShortLabel = "Attach to micro chat";
			w1.Add (this.AttachToMicroChatAction, null);
			this.DetachFromMicroChatAction = new global::Gtk.Action ("DetachFromMicroChatAction", "Detach from micro chat", null, null);
			this.DetachFromMicroChatAction.ShortLabel = "Detach from micro chat";
			w1.Add (this.DetachFromMicroChatAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Client.Forms.Main";
			this.Title = "Pidgeon Client";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Client.Resources.pigeon_clip_art_hight.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.Forms.Main.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='OpenNewConnectionAction1' action='OpenNewConnectionAction1'/><separator/><menuitem name='FavoriteNetworksAction' action='FavoriteNetworksAction'/><separator/><menuitem name='PreferencesAction' action='PreferencesAction'/><separator/><menuitem name='ShutDownAction' action='ShutDownAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='PacketViewerAction' action='PacketViewerAction'/><menuitem name='SkinEditorAction' action='SkinEditorAction'/><menuitem name='SmallChatAction' action='SmallChatAction'/><separator/><menuitem name='AttachToMicroChatAction' action='AttachToMicroChatAction'/><menuitem name='DetachFromMicroChatAction' action='DetachFromMicroChatAction'/></menu><menu name='MIscAction' action='MIscAction'><menuitem name='SearchAction' action='SearchAction'/><separator/><menuitem name='SwitchToAdvancedLayoutAction' action='SwitchToAdvancedLayoutAction'/><menuitem name='ConfigurationFileAction' action='ConfigurationFileAction'/></menu><menu name='ShowAction' action='ShowAction'><menuitem name='RootAction' action='RootAction'/></menu><menu name='UserAction' action='UserAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/><menuitem name='HelpAction1' action='HelpAction1'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox3.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 183;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.pidgeonlist1 = new global::Client.Graphics.PidgeonList ();
			this.pidgeonlist1.Events = ((global::Gdk.EventMask)(256));
			this.pidgeonlist1.Name = "pidgeonlist1";
			this.hpaned1.Add (this.pidgeonlist1);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.pidgeonlist1]));
			w3.Resize = false;
			this.vbox3.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hpaned1]));
			w4.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.statusbar3 = new global::Gtk.Statusbar ();
			this.statusbar3.Name = "statusbar3";
			this.statusbar3.Spacing = 6;
			this.vbox3.Add (this.statusbar3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.statusbar3]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1018;
			this.DefaultHeight = 600;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.Unshow);
			this.ShutDownAction.Activated += new global::System.EventHandler (this.shutDownToolStripMenuItem_Click);
			this.AboutAction.Activated += new global::System.EventHandler (this.aboutToolStripMenuItem_Click);
			this.PreferencesAction.Activated += new global::System.EventHandler (this.preferencesToolStripMenuItem_Click);
		}
	}
}
