
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
    /// <summary>
    /// List of networks
    /// </summary>
    public partial class NetworkDB
    {
        private void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget Client.Forms.NetworkDB
            this.Name = "Client.Forms.NetworkDB";
            this.Title = "NetworkDB";
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 456;
            this.DefaultHeight = 336;
            this.Show ();
        }
    }
}
