
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
    public partial class ConfigFile
    {
        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget Client.Forms.ConfigFile
            this.Name = "Client.Forms.ConfigFile";
            this.Title = "ConfigFile";
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show ();
        }
    }
}
