
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Graphics
{
	public partial class Window
	{
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.HPaned hpaned1;
		private global::Client.ScrollbackWidget scrollbackwidget1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeview2;
		private global::Client.Graphics.TextBox textbox1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Graphics.Window
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.Graphics.Window";
			// Container child Client.Graphics.Window.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 319;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 333;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.scrollbackwidget1 = new global::Client.ScrollbackWidget ();
			this.scrollbackwidget1.Events = ((global::Gdk.EventMask)(256));
			this.scrollbackwidget1.Name = "scrollbackwidget1";
			this.hpaned1.Add (this.scrollbackwidget1);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.scrollbackwidget1]));
			w1.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow1.Add (this.treeview2);
			this.hpaned1.Add (this.GtkScrolledWindow1);
			this.vpaned1.Add (this.hpaned1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned1]));
			w4.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.textbox1 = new global::Client.Graphics.TextBox ();
			this.textbox1.Events = ((global::Gdk.EventMask)(256));
			this.textbox1.Name = "textbox1";
			this.vpaned1.Add (this.textbox1);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
