
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class ScrollbackWidget
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView simpleview;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.ScrollbackWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.ScrollbackWidget";
			// Container child Client.ScrollbackWidget.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.simpleview = new global::Gtk.TextView ();
			this.simpleview.CanFocus = true;
			this.simpleview.Name = "simpleview";
			this.GtkScrolledWindow.Add (this.simpleview);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
