
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
    public partial class ScriptEdit
    {
        private global::Gtk.VBox vbox1;
        private global::Gtk.Label label1;
        private global::Gtk.ScrolledWindow GtkScrolledWindow;
        private global::Gtk.TextView textview1;
        private global::Gtk.HBox hbox1;
        private global::Gtk.Button button2;
        private global::Gtk.Button button1;
        
        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget Client.Forms.ScriptEdit
            this.Name = "Client.Forms.ScriptEdit";
            this.Title = "ScriptEdit";
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child Client.Forms.ScriptEdit.Gtk.Container+ContainerChild
            this.vbox1 = new global::Gtk.VBox ();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new global::Gtk.Label ();
            this.label1.Name = "label1";
            this.label1.LabelProp = "Do you really want to execute following commands?\r\n\r\nLines prefixed with following symbols are:\r\n# - comment\r\n/ - will be launched as pidgeon command\r\n\r\nOther lines will be delivered as raw command to server";
            this.vbox1.Add (this.label1);
            global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.textview1 = new global::Gtk.TextView ();
            this.textview1.CanFocus = true;
            this.textview1.Name = "textview1";
            this.GtkScrolledWindow.Add (this.textview1);
            this.vbox1.Add (this.GtkScrolledWindow);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
            w3.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new global::Gtk.HBox ();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button2 = new global::Gtk.Button ();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            this.button2.Label = "Execute";
            this.hbox1.Add (this.button2);
            global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button1 = new global::Gtk.Button ();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Label = "Abort";
            this.hbox1.Add (this.button1);
            global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox1.Add (this.hbox1);
            global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            this.Add (this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 737;
            this.DefaultHeight = 432;
            this.Show ();
        }
    }
}
