
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Graphics
{
	public partial class TextBox
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Entry richTextBox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Graphics.TextBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.Graphics.TextBox";
			// Container child Client.Graphics.TextBox.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.richTextBox = new global::Gtk.Entry ();
			this.richTextBox.CanFocus = true;
			this.richTextBox.Name = "richTextBox";
			this.richTextBox.IsEditable = true;
			this.richTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.richTextBox);
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
