
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
	public partial class Connection
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Forms.Connection
			this.Name = "Client.Forms.Connection";
			this.Title = "Connection";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Client.Resources.pigeon_clip_art_hight.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 833;
			this.DefaultHeight = 362;
			this.Show ();
		}
	}
}
