
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
	public partial class Connection
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Forms.Connection
			this.Name = "Client.Forms.Connection";
			this.Title = global::Mono.Unix.Catalog.GetString ("Connection");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
