
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Graphics
{
	public partial class PidgeonList
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Graphics.PidgeonList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.Graphics.PidgeonList";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
