
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class Scrollback
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Scrollback
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.Scrollback";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
