
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Graphics
{
	public partial class TextBox
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView richTextBox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Client.Graphics.TextBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Client.Graphics.TextBox";
			// Container child Client.Graphics.TextBox.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.richTextBox = new global::Gtk.TextView ();
			this.richTextBox.CanFocus = true;
			this.richTextBox.Name = "richTextBox";
			this.richTextBox.AcceptsTab = false;
			this.GtkScrolledWindow.Add (this.richTextBox);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
