
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Forms
{
    public partial class Main
    {
        private global::Gtk.UIManager UIManager;
        public global::Gtk.Action FileAction;
        public global::Gtk.Action ShutDownAction;
        public global::Gtk.Action ToolsAction;
        public global::Gtk.Action MiscAction;
        public global::Gtk.Action ShowAction;
        public global::Gtk.Action UserAction;
        public global::Gtk.Action HelpAction;
        public global::Gtk.Action AboutAction;
        public global::Gtk.Action ContentsAction;
        public global::Gtk.Action RootAction;
        public global::Gtk.Action SearchAction;
        public global::Gtk.Action SwitchToAdvancedLayoutAction;
        public global::Gtk.Action ConfigurationFileAction;
        public global::Gtk.Action OpenNewConnectionAction;
        public global::Gtk.Action OpenNewConnectionAction1;
        public global::Gtk.Action FavoriteNetworksAction;
        public global::Gtk.Action PreferencesAction;
        public global::Gtk.Action PacketViewerAction;
        public global::Gtk.Action SkinEditorAction;
        public global::Gtk.Action SmallChatAction;
        public global::Gtk.Action AttachToMicroChatAction;
        public global::Gtk.Action DetachFromMicroChatAction;
        private global::Gtk.VBox vbox3;
        public global::Gtk.MenuBar menubar2;
        private global::Gtk.HPaned hpaned1;
        private global::Client.Graphics.PidgeonList pidgeonlist1;
        public global::Gtk.Statusbar toolStrip;
        public global::Gtk.Label toolStripStatusNetwork;
        public global::Gtk.Label toolStripStatusChannel;
        public global::Gtk.Label toolStripInfo;
        public global::Gtk.ProgressBar toolStripProgressBar1;
        
        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget Client.Forms.Main
            this.UIManager = new global::Gtk.UIManager ();
            global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
            this.FileAction = new global::Gtk.Action ("FileAction", "File", null, null);
            this.FileAction.ShortLabel = "File";
            w1.Add (this.FileAction, null);
            this.ShutDownAction = new global::Gtk.Action ("ShutDownAction", "Shut down", null, null);
            this.ShutDownAction.ShortLabel = "Shut down";
            w1.Add (this.ShutDownAction, null);
            this.ToolsAction = new global::Gtk.Action ("ToolsAction", "Tools", null, null);
            this.ToolsAction.ShortLabel = "Tools";
            w1.Add (this.ToolsAction, null);
            this.MiscAction = new global::Gtk.Action ("MiscAction", "Misc", null, null);
            this.MiscAction.ShortLabel = "Misc";
            w1.Add (this.MiscAction, null);
            this.ShowAction = new global::Gtk.Action ("ShowAction", "Show", null, null);
            this.ShowAction.ShortLabel = "Show";
            w1.Add (this.ShowAction, null);
            this.UserAction = new global::Gtk.Action ("UserAction", "User", null, null);
            this.UserAction.ShortLabel = "User";
            this.UserAction.Visible = false;
            w1.Add (this.UserAction, null);
            this.HelpAction = new global::Gtk.Action ("HelpAction", "Help", null, null);
            this.HelpAction.ShortLabel = "Help";
            w1.Add (this.HelpAction, null);
            this.AboutAction = new global::Gtk.Action ("AboutAction", "About", null, null);
            this.AboutAction.ShortLabel = "About";
            w1.Add (this.AboutAction, null);
            this.ContentsAction = new global::Gtk.Action ("ContentsAction", "Contents", null, null);
            this.ContentsAction.ShortLabel = "Help";
            w1.Add (this.ContentsAction, "F1");
            this.RootAction = new global::Gtk.Action ("RootAction", "Root", null, null);
            this.RootAction.ShortLabel = "Root";
            w1.Add (this.RootAction, null);
            this.SearchAction = new global::Gtk.Action ("SearchAction", "Search", null, null);
            this.SearchAction.ShortLabel = "Search";
            w1.Add (this.SearchAction, "<Primary>f");
            this.SwitchToAdvancedLayoutAction = new global::Gtk.Action ("SwitchToAdvancedLayoutAction", "Switch to advanced layout", null, null);
            this.SwitchToAdvancedLayoutAction.ShortLabel = "Switch to advanced layout";
            w1.Add (this.SwitchToAdvancedLayoutAction, null);
            this.ConfigurationFileAction = new global::Gtk.Action ("ConfigurationFileAction", "Configuration file", null, null);
            this.ConfigurationFileAction.ShortLabel = "Configuration file";
            w1.Add (this.ConfigurationFileAction, null);
            this.OpenNewConnectionAction = new global::Gtk.Action ("OpenNewConnectionAction", "Open new connection", null, null);
            this.OpenNewConnectionAction.ShortLabel = "Open new connection";
            w1.Add (this.OpenNewConnectionAction, null);
            this.OpenNewConnectionAction1 = new global::Gtk.Action ("OpenNewConnectionAction1", "Open new connection", null, null);
            this.OpenNewConnectionAction1.ShortLabel = "Open new connection";
            w1.Add (this.OpenNewConnectionAction1, "<Alt>n");
            this.FavoriteNetworksAction = new global::Gtk.Action ("FavoriteNetworksAction", "Favorite networks", null, null);
            this.FavoriteNetworksAction.ShortLabel = "Favorite networks";
            w1.Add (this.FavoriteNetworksAction, null);
            this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", "Preferences", null, null);
            this.PreferencesAction.ShortLabel = "Preferences";
            w1.Add (this.PreferencesAction, "<Alt>p");
            this.PacketViewerAction = new global::Gtk.Action ("PacketViewerAction", "Packet viewer", null, null);
            this.PacketViewerAction.ShortLabel = "Packet viewer";
            w1.Add (this.PacketViewerAction, "<Primary><Alt>p");
            this.SkinEditorAction = new global::Gtk.Action ("SkinEditorAction", "Skin editor", null, null);
            this.SkinEditorAction.ShortLabel = "Skin editor";
            w1.Add (this.SkinEditorAction, null);
            this.SmallChatAction = new global::Gtk.Action ("SmallChatAction", "Small chat", null, null);
            this.SmallChatAction.ShortLabel = "Small chat";
            w1.Add (this.SmallChatAction, null);
            this.AttachToMicroChatAction = new global::Gtk.Action ("AttachToMicroChatAction", "Attach to micro chat", null, null);
            this.AttachToMicroChatAction.ShortLabel = "Attach to micro chat";
            w1.Add (this.AttachToMicroChatAction, "<Alt>m");
            this.DetachFromMicroChatAction = new global::Gtk.Action ("DetachFromMicroChatAction", "Detach from micro chat", null, null);
            this.DetachFromMicroChatAction.ShortLabel = "Detach from micro chat";
            w1.Add (this.DetachFromMicroChatAction, "<Alt>d");
            this.UIManager.InsertActionGroup (w1, 0);
            this.AddAccelGroup (this.UIManager.AccelGroup);
            this.Name = "Client.Forms.Main";
            this.Title = "Pidgeon Client";
            this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Client.Resources.pigeon_clip_art_hight.ico");
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child Client.Forms.Main.Gtk.Container+ContainerChild
            this.vbox3 = new global::Gtk.VBox ();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='OpenNewConnectionAction1' action='OpenNewConnectionAction1'/><separator/><menuitem name='FavoriteNetworksAction' action='FavoriteNetworksAction'/><separator/><menuitem name='PreferencesAction' action='PreferencesAction'/><separator/><menuitem name='ShutDownAction' action='ShutDownAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='PacketViewerAction' action='PacketViewerAction'/><menuitem name='SmallChatAction' action='SmallChatAction'/><separator/><menuitem name='AttachToMicroChatAction' action='AttachToMicroChatAction'/><menuitem name='DetachFromMicroChatAction' action='DetachFromMicroChatAction'/></menu><menu name='MiscAction' action='MiscAction'><menuitem name='SearchAction' action='SearchAction'/><separator/><menuitem name='ConfigurationFileAction' action='ConfigurationFileAction'/></menu><menu name='ShowAction' action='ShowAction'><menuitem name='RootAction' action='RootAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/><menuitem name='ContentsAction' action='ContentsAction'/></menu></menubar></ui>");
            this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
            this.menubar2.Name = "menubar2";
            this.vbox3.Add (this.menubar2);
            global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar2]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hpaned1 = new global::Gtk.HPaned ();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 183;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.pidgeonlist1 = new global::Client.Graphics.PidgeonList ();
            this.pidgeonlist1.Events = ((global::Gdk.EventMask)(256));
            this.pidgeonlist1.Name = "pidgeonlist1";
            this.hpaned1.Add (this.pidgeonlist1);
            global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.pidgeonlist1]));
            w3.Resize = false;
            this.vbox3.Add (this.hpaned1);
            global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hpaned1]));
            w4.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.toolStrip = new global::Gtk.Statusbar ();
            this.toolStrip.Name = "toolStrip";
            this.toolStrip.Spacing = 6;
            // Container child toolStrip.Gtk.Box+BoxChild
            this.toolStripStatusNetwork = new global::Gtk.Label ();
            this.toolStripStatusNetwork.Name = "toolStripStatusNetwork";
            this.toolStrip.Add (this.toolStripStatusNetwork);
            global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.toolStrip [this.toolStripStatusNetwork]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child toolStrip.Gtk.Box+BoxChild
            this.toolStripStatusChannel = new global::Gtk.Label ();
            this.toolStripStatusChannel.Name = "toolStripStatusChannel";
            this.toolStrip.Add (this.toolStripStatusChannel);
            global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.toolStrip [this.toolStripStatusChannel]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child toolStrip.Gtk.Box+BoxChild
            this.toolStripInfo = new global::Gtk.Label ();
            this.toolStripInfo.Name = "toolStripInfo";
            this.toolStrip.Add (this.toolStripInfo);
            global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.toolStrip [this.toolStripInfo]));
            w7.Position = 3;
            w7.Expand = false;
            w7.Fill = false;
            // Container child toolStrip.Gtk.Box+BoxChild
            this.toolStripProgressBar1 = new global::Gtk.ProgressBar ();
            this.toolStripProgressBar1.Name = "toolStripProgressBar1";
            this.toolStrip.Add (this.toolStripProgressBar1);
            global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.toolStrip [this.toolStripProgressBar1]));
            w8.Position = 4;
            this.vbox3.Add (this.toolStrip);
            global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolStrip]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            this.Add (this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 1018;
            this.DefaultHeight = 600;
            this.Show ();
            this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.Unshow);
            this.ShutDownAction.Activated += new global::System.EventHandler (this.shutDownToolStripMenuItem_Click);
            this.AboutAction.Activated += new global::System.EventHandler (this.aboutToolStripMenuItem_Click);
            this.OpenNewConnectionAction1.Activated += new global::System.EventHandler (this.newConnectionToolStripMenuItem_Click_1);
            this.PreferencesAction.Activated += new global::System.EventHandler (this.preferencesToolStripMenuItem_Click);
            this.PacketViewerAction.Activated += new global::System.EventHandler (this.toolStripMenuItem3_Click);
            this.SmallChatAction.Activated += new global::System.EventHandler (this.taskbarBoxToolStripMenuItem_Click);
            this.AttachToMicroChatAction.Activated += new global::System.EventHandler (this.attachToMicroChatToolStripMenuItem_Click);
            this.DetachFromMicroChatAction.Activated += new global::System.EventHandler (this.detachFromMicroChatToolStripMenuItem_Click);
        }
    }
}
