//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window-menu-file=File;
        ///window-menu-quit=Exit;
        ///window-menu-conf=Nastaveni;
        ///window-menu-help=Napoveda;
        ///pidgeon-shut=Do you really want to exit?;
        ///invalid-server=This is not a valid server name;
        ///invalid-command=Invalid command;
        ///loading-server=Connecting to $1;
        ///nick-e1=This is not a valid nick;
        ///nick=Your nick has been set;
        ///invalid-channel=This is not a valid channel;
        ///error1=You need to be connected;
        ///join=$1 just joined the channel;
        ///left=The $1 just left the channel;
        ///topic-data=Topic was set at $2 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cs_czech {
            get {
                return ResourceManager.GetString("cs_czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window-menu-file=File;
        ///window-menu-quit=Exit;
        ///window-menu-conf=Preferences;
        ///window-menu-help=Help;
        ///pidgeon-shut=Do you really want to exit?;
        ///invalid-server=This is not a valid server name;
        ///invalid-command=Invalid command;
        ///loading-server=Connecting to $1;
        ///nick-e1=This is not a valid nick;
        ///nick=Your nick has been set;
        ///invalid-channel=This is not a valid channel;
        ///error1=You need to be connected;
        ///join=$1 just joined the channel;
        ///left=The $1 just left the channel;
        ///topic-data=Topic was set at $2 by  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_english {
            get {
                return ResourceManager.GetString("en_english", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
