Document: pidgeon
Title: Debian pidgeon Manual
Author: <insert document author here>
Abstract: This manual describes what pidgeon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pidgeon/pidgeon.sgml.gz

Format: postscript
Files: /usr/share/doc/pidgeon/pidgeon.ps.gz

Format: text
Files: /usr/share/doc/pidgeon/pidgeon.text.gz

Format: HTML
Index: /usr/share/doc/pidgeon/html/index.html
Files: /usr/share/doc/pidgeon/html/*.html
